heat_template_version: 2016-10-14

description: Template create vm.

#####################################
# PARAMETERS
#####################################
parameters:
  key_name:
    type: string
    label: Key Name
    description: Key name 
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Centos based image.
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
  private_network:
    type: string
    label: Private Network
    description: Setup Private network
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
    default: Public_Network
  username:
    type: string
    label: Set Username
    description: Set username to virtual machine.
  security_group:
    type: string
    label: Set security group
    default: Default
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  floating_ip:
    type: number
    description: Do you use Floating IP?
    default: 1

conditions:
  create_security_group: {equals: [{get_param: security_group}, "Default"]}
  do_not_set_availability_zone: {equals: [{get_param: availability_zone}, "Default"]}
  use_floating_ip: {equals : [{get_param: floating_ip}, 1]}

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        list_join: [-, [{ get_param: 'OS::stack_name' },neo,secgroup]]
      rules:
        - protocol: icmp
        - protocol: udp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_mode: remote_group_id
    condition: create_security_group
  define_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: private_network }
      security_groups:
        - {if: ["create_security_group", {get_resource: secgroup}, {get_param: security_group}]}
       
  floating:
      type: OS::Neutron::FloatingIP
      condition: use_floating_ip
      properties:
        floating_network: {get_param: public_network}
        port_id: {get_resource: define_port}

  cloud_config:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config:
            str_replace:
              params:
                $USERNAME : { get_param: username }
              template: |
                #cloud-config
                system_info:
                  default_user:
                    name: $USERNAME
                    lock_passwd: true
                    gecos: Instances Interactive User
                    groups: [wheel, adm, systemd-journal]
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash

  create_vm:
    type: OS::Nova::Server
    properties:
      name: { get_param: 'OS::stack_name' }
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
        - port: {get_resource: define_port}
      user_data_format: RAW
      user_data: {get_resource: cloud_config}
      availability_zone: {if: ["do_not_set_availability_zone", null ,{get_param: availability_zone}]}
outputs:
  user:
    description: User Name
    value: {get_param: username}
  controller:
    condition: get_floating_ip
    description: Controller IP
    value: {get_attr: [floating,floating_ip_address]}
  key_name:
    description: Key Name
    value: {get_param: key_name}
  sec_group:
    description: Security Group
    value: {if: ["create_security_group", {list_join: [-, [{ get_param: 'OS::stack_name' },neo,secgroup]]}, {get_param: security_group}]}
  vm_id:
    description: VM ID
    value: {get_resource: create_vm}